<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\Relations\BelongsTo;
use Illuminate\Database\Eloquent\Relations\MorphToMany;

class FavoriteProduct extends Model
{
    use HasFactory;

    protected $fillable = [
        'id',
        'name',
        'product1_id',
        'product2_id',
        'product3_id',
    ];

    protected static function boot()
    {
        parent::boot(); // TODO: Change the autogenerated stub

        static::deleting(function ($model) {
            $model->categories()->detach();
        });
    }

    public function product1(): BelongsTo
    {
        return $this->belongsTo(Product::class, 'product1_id');
    }

    public function product2(): BelongsTo
    {
        return $this->belongsTo(Product::class, 'product2_id');
    }

    public function product3(): BelongsTo
    {
        return $this->belongsTo(Product::class, 'product3_id');
    }

    public function categories(): MorphToMany
    {
        return $this->morphToMany(Category::class, 'categoryable')
            ->using(Categoryable::class);
    }
}
